# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bluemellophone/code/pyrf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bluemellophone/code/pyrf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bluemellophone/code/pyrf/CMakeFiles /Users/bluemellophone/code/pyrf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bluemellophone/code/pyrf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyrf

# Build rule for target.
pyrf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyrf
.PHONY : pyrf

# fast build rule for target.
pyrf/fast:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/build
.PHONY : pyrf/fast

src/CRForestDetector.o: src/CRForestDetector.cpp.o
.PHONY : src/CRForestDetector.o

# target to build an object file
src/CRForestDetector.cpp.o:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRForestDetector.cpp.o
.PHONY : src/CRForestDetector.cpp.o

src/CRForestDetector.i: src/CRForestDetector.cpp.i
.PHONY : src/CRForestDetector.i

# target to preprocess a source file
src/CRForestDetector.cpp.i:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRForestDetector.cpp.i
.PHONY : src/CRForestDetector.cpp.i

src/CRForestDetector.s: src/CRForestDetector.cpp.s
.PHONY : src/CRForestDetector.s

# target to generate assembly for a file
src/CRForestDetector.cpp.s:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRForestDetector.cpp.s
.PHONY : src/CRForestDetector.cpp.s

src/CRPatch.o: src/CRPatch.cpp.o
.PHONY : src/CRPatch.o

# target to build an object file
src/CRPatch.cpp.o:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRPatch.cpp.o
.PHONY : src/CRPatch.cpp.o

src/CRPatch.i: src/CRPatch.cpp.i
.PHONY : src/CRPatch.i

# target to preprocess a source file
src/CRPatch.cpp.i:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRPatch.cpp.i
.PHONY : src/CRPatch.cpp.i

src/CRPatch.s: src/CRPatch.cpp.s
.PHONY : src/CRPatch.s

# target to generate assembly for a file
src/CRPatch.cpp.s:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRPatch.cpp.s
.PHONY : src/CRPatch.cpp.s

src/CRTree.o: src/CRTree.cpp.o
.PHONY : src/CRTree.o

# target to build an object file
src/CRTree.cpp.o:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRTree.cpp.o
.PHONY : src/CRTree.cpp.o

src/CRTree.i: src/CRTree.cpp.i
.PHONY : src/CRTree.i

# target to preprocess a source file
src/CRTree.cpp.i:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRTree.cpp.i
.PHONY : src/CRTree.cpp.i

src/CRTree.s: src/CRTree.cpp.s
.PHONY : src/CRTree.s

# target to generate assembly for a file
src/CRTree.cpp.s:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/CRTree.cpp.s
.PHONY : src/CRTree.cpp.s

src/HoG.o: src/HoG.cpp.o
.PHONY : src/HoG.o

# target to build an object file
src/HoG.cpp.o:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/HoG.cpp.o
.PHONY : src/HoG.cpp.o

src/HoG.i: src/HoG.cpp.i
.PHONY : src/HoG.i

# target to preprocess a source file
src/HoG.cpp.i:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/HoG.cpp.i
.PHONY : src/HoG.cpp.i

src/HoG.s: src/HoG.cpp.s
.PHONY : src/HoG.s

# target to generate assembly for a file
src/HoG.cpp.s:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/HoG.cpp.s
.PHONY : src/HoG.cpp.s

src/pyrf.o: src/pyrf.cpp.o
.PHONY : src/pyrf.o

# target to build an object file
src/pyrf.cpp.o:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/pyrf.cpp.o
.PHONY : src/pyrf.cpp.o

src/pyrf.i: src/pyrf.cpp.i
.PHONY : src/pyrf.i

# target to preprocess a source file
src/pyrf.cpp.i:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/pyrf.cpp.i
.PHONY : src/pyrf.cpp.i

src/pyrf.s: src/pyrf.cpp.s
.PHONY : src/pyrf.s

# target to generate assembly for a file
src/pyrf.cpp.s:
	$(MAKE) -f CMakeFiles/pyrf.dir/build.make CMakeFiles/pyrf.dir/src/pyrf.cpp.s
.PHONY : src/pyrf.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pyrf"
	@echo "... rebuild_cache"
	@echo "... src/CRForestDetector.o"
	@echo "... src/CRForestDetector.i"
	@echo "... src/CRForestDetector.s"
	@echo "... src/CRPatch.o"
	@echo "... src/CRPatch.i"
	@echo "... src/CRPatch.s"
	@echo "... src/CRTree.o"
	@echo "... src/CRTree.i"
	@echo "... src/CRTree.s"
	@echo "... src/HoG.o"
	@echo "... src/HoG.i"
	@echo "... src/HoG.s"
	@echo "... src/pyrf.o"
	@echo "... src/pyrf.i"
	@echo "... src/pyrf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

